# Database Configuration
spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # JPA / Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Application Name
  application:
    name: ${SERVICE_NAME}

# Server Configuration
server:
  port: ${SERVER_PORT}

# Logging Configuration
logging:
  level:
    org:
      springframework: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
    com:
      mohammedsaqibkhan: ${LOGGING_LEVEL_CUSTOM_PACKAGE}
    feign:
      client: ${LOGGING_LEVEL_FEIGN_CLIENT}
    springframework:
      web: ${LOGGING_LEVEL_SPRING_WEB}

# API Keys
nutritionix:
  app:
    id: ${NUTRITIONIX_APP_ID}
    key: ${NUTRITIONIX_APP_KEY}
