spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    protocol: ${EMAIL_PROTOCOL}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_SMTP_AUTH}
          starttls:
            enable: ${EMAIL_SMTP_STARTTLS_ENABLE}
            required: ${EMAIL_SMTP_STARTTLS_REQUIRED}
          connectiontimeout: ${EMAIL_SMTP_CONNECTIONTIMEOUT}
          timeout: ${EMAIL_SMTP_TIMEOUT}
          writetimeout: ${EMAIL_SMTP_WRITETIMEOUT}

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

# Server Configuration
server:
  port: ${SERVER_PORT}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG


